name: sandbox-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - numpy=1.22.2
  - pandas=1.4.1
  - scipy
  - matplotlib
  - netCDF4
  - cartopy
  - metpy=1.4.0
  - tensorflow=2.12.0
  - pyresample=1.27.1
  - nbgitpuller
